# Generated by Django 5.1.4 on 2024-12-10 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []


    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=70)),
                ('NumberofDepartments', models.IntegerField(default=0, editable=False)),
                ('NumberofEmployees', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=70)),
                ('EmailAddress', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=70)),
                ('NumberofEmployees', models.IntegerField(default=0, editable=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='API.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeStatus', models.CharField(max_length=70)),
                ('EmployeeName', models.CharField(max_length=70)),
                ('EmailAddress', models.EmailField(max_length=254, unique=True)),
                ('MobileNumber', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{10,15}$')])),
                ('Address', models.CharField(max_length=300)),
                ('Designation', models.CharField(max_length=70)),
                ('HiredOn', models.DateTimeField(blank=True, null=True)),
                ('DaysEmployed', models.IntegerField(default=0, editable=False)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='API.company')),
                ('Department', models.ForeignKey(limit_choices_to=models.Q(('Company', models.F('Company'))), on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='API.department')),
            ],
        ),
    ]
