# Generated by Django 5.1.4 on 2024-12-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='NumberofDepartments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='NumberofEmployees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='NumberofEmployees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='DaysEmployed',
            field=models.IntegerField(default=0),
        ),
    ]
